### PR TITLE
PANDARIA: fix cve problem

### PR DESCRIPTION
**Pull request by GGGitBoy**
**Relate issue**
https://github.com/cnrancher/pandaria-images-scanning/issues/82

### CODE REVIEW

**Comment by orangedeng** [comment]
Can we upgrade to golang 1.18+?

**Comment by GGGitBoy** [comment]
已更新，跟 rancher 一样使用 golang 1.19

**Review by Jason-ZW — COMMENTED** [review]
LGTM

**Comment by orangedeng** [comment]
LGTM

**Comment by Jason-ZW** [comment]
https://github.com/rancher/webhook-receiver/pull/11/files 上游也注意到了cve问题并进行修复，可能需要参考下上游修改

**Pull request merged**
